version: '3.9'
services:
  
  db:
    image: mysql:8.0 
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: exam           
      MYSQL_USER: user
      MYSQL_PASSWORD: 12345678
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-container
    ports:
      - "3000:3000"
    # environment:
    #   NODE_ENV: production
    #   DB_HOST: db                # 服務名稱對應 MySQL 的容器名稱
    #   DB_PORT: 3306
    #   DB_USER: user
    #   DB_PASSWORD: 12345678
    #   DB_NAME: exam
    depends_on:
      - db                       # 確保 app 啟動前，db 已啟動
    command: >
      sh -c "npx sequelize-cli db:seed:undo:all && 
      npx sequelize-cli db:migrate:undo:all &&
      npx sequelize-cli db:migrate && 
      npx sequelize-cli db:seed:all &&
      node dist/main" 
volumes:
  mysql_data:
